services:
  web:
    build:
     context: .
    image: elevate-web
    container_name: elevate-web
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore: 
            -node_modules
        - action: rebuild
          path: package.json